### ISSUE TITLE
Create better targeting in tops

### ISSUE THREAD

**Issue by xbc5** [xbc5/sys-config#79]
Move towards using `qubesctl --targes foo`, where the top file looks like:
```yaml
user:
  dom0:
    - ...
  qubes:type:template:
    - ...
  qubes:type:appvm:
    - ...
```

Such that you can apply a set of states to any VM, just by providing its name (i.e. not hard-coding te targets).

Right now, for example, the current system requires a state file for every domain that you wish to apply a service to -- e.g. `vms/dev/docker.sls`.
